version: '3'
services:
  scheduler:
    image: 'mcuadros/ofelia:latest'
    command: 'daemon --docker'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      ofelia.job-run.my-run-job.schedule: '@every 24h'
      ofelia.job-run.my-run-job.image: 'ghcr.io/sjkp/skaanetrafiken-and-booli:sha-12ab072'
      ofelia.job-run.my-run-job.environment: '["SMTP_HOST=localhost","SMTP_PORT=465","SMTP_SECURE=true","SMTP_USER=email@email.com","SMTP_PASS=pass","EMAIL_FROM=email@email.com","EMAIL_TO=email@email.com","EMAIL_SUBJECT=New Properties in Skåne - Villa, Fritidshus, Gård"]'
