version: '3'
services:
  app:
    image: 'ghcr.io/sjkp/skaanetrafiken-and-booli:sha-d2f9591'
    container_name: app_app_1
    restart: 'no'
  restarter:
    image: 'docker:cli'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command:
      - /bin/sh
      - '-c'
      - 'while true; do sleep 86400; docker restart app_app_1; done'
    restart: unless-stopped